### ISSUE TITLE
Missing transpose

### ISSUE THREAD

**Issue by idc9** [mathurinm/andersoncd#24]
There is a transpose missing in https://github.com/mathurinm/andersoncd/blob/af2123b241e5f82f7c51b2bbf5196fb02723b582/andersoncd/weighted_lasso.py#L227

i.e. this line should read as

```python
alpha_max = np.max(np.abs(X[:, penalized].T @ y / weights[penalized])) / n_samples
```

**Comment by mathurinm** [comment]
Thanks Iain, you're right ! This part of the code probably isn't covered by tests.

Can you send a quick PR to fix the transpose ?
