### ISSUE TITLE
type issue with WeightedL1 penalty

### ISSUE THREAD

**Issue by idc9** [mathurinm/andersoncd#51]
The `WeightedL1` penalty is unhappy when the weights argument is not a float.

```python
from andersoncd.penalties import WeightedL1

# this is fine
penalty = WeightedL1(alpha=1, weights=np.arange(10).astype(float))

# this throws an error
penalty = WeightedL1(alpha=1, weights=np.arange(10))
```

This is a minor issue that won't come up often, but may cause headaches with the `WeightedLasso` class. May be worth fixing at some point e.g. add automatic conversion to float.

**Comment by mathurinm** [comment]
I have fixed by simply casting weights it to a float64 array

It still needs an array to work; I don't think it's worth doing more since it's a weighted penalty, and so people who use it are aware that they need to pass weights
